[tool]
[tool.poetry]
authors = ["elisttm"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
flask-session = "^0.3.2"
waitress = "^1.4.4"
tinydb = "^4.1.1"
